apiVersion: platform.kratix.io/v1alpha1
kind: Destination
metadata:
   name: worker-cluster
   labels:
    environment: dev
spec:
  path: worker-cluster
  stateStoreRef:
     name: default
     kind: BucketStateStore
